const actionsEnum = {
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    SET_USER_INFO: 'SET_USER_INFO',
    SET_USER_PLAYLISTS: 'SET_USER_PLAYLISTS',
    SET_USER_TOP_ARTISTS: 'SET_USER_TOP_ARTISTS',
    SET_USER_TOP_TRACKS: 'SET_USER_TOP_TRACKS',
    SET_AUDIO_FEATURES: 'SET_AUDIO_FEATURES',
    SET_RECOMMEDATIONS: 'SET_RECOMMENDATIONS',
    SET_CUSTOM_PLAYLIST: 'SET_CUSTOM_PLAYLIST'
}

export default actionsEnum;